[package]
name = "wordle"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
console = "0.16.1"
<<<<<<< HEAD
rand = "0.9.2"
=======
crossterm = "0.29.0"
>>>>>>> refs/remotes/origin/main
